server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: service-userEntity
          uri: lb://service-userEntity
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/userentity
        - id: service-security
          uri: lb://service-security
          predicates:
           - Path=/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: securityServiceCircuitBreaker
                fallbackUri: forward:/fallback/security
        - id: service-employee
          uri: lb://service-employee
          predicates:
           - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: employeeServiceCircuitBreaker
                fallbackUri: forward:/fallback/employee
        - id: service-dateEntity
          uri: lb://service-dateEntity
          predicates:
            - Path=/dates/**
          filters:
            - name: CircuitBreaker
              args:
                name: dateServiceCircuitBreaker
                fallbackUri: forward:/fallback/dateentity
        - id: service-appointment
          uri: lb://service-appointment
          predicates:
            - Path=/appointments/**
          filters:
            - name: CircuitBreaker
              args:
                name: dateServiceCircuitBreaker
                fallbackUri: forward:/fallback/appointment
jwt:
  public-key: ${JWT_PUBLIC_KEY}