server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: service-userEntity
          uri: lb://service-user
          predicates:
           - Path=/**
        - id: service-security
          uri: lb://service-security
          predicates:
           - Path=/**
        - id: service-employee
          uri: lb://service-employee
          predicates:
           - Path=/**
        - id: service-dateEntity
          uri: lb://service-date
          predicates:
          - Path=/**
        #- id: department-service
        # uri: lb://department-service
        # predicates:
      #   - Path=/api/v1/department/**
jwt:
  public-key: ${JWT_PUBLIC_KEY}