server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    gateway:
      routes:
        - id: service-userEntity
          uri: lb://service-user
          predicates:
           - Path=/**
        #- id: department-service
        # uri: lb://department-service
        # predicates:
      #   - Path=/api/v1/department/**